
# --- FlowOne local: HTTP listener on :80 -> flowone vhost ---
virtualhost flowone {
  vhRoot                  /var/www/html/backend
  configFile              $SERVER_ROOT/conf/vhosts/flowone/vhconf.conf
  allowSymbolLink         1
  enableScript            1
  restrained              0
}

listener flowoneHTTP {
  address                 *:80
  secure                  0
  map                     flowone *
}
