/**
 * Collab Auth Handler
 * 
 * Handles WebSocket authentication for the collaboration server.
 * Verifies JWT tokens using RS256 (public key) with HS256 fallback during migration.
 * Tokens are always generated by the PHP backend.
 */

import jwt from 'jsonwebtoken'
import { COLLAB_ROLES, COLLAB_ROLE_CAPABILITIES, getCollabUserColor } from '../config.js'
import { logAuthEvent } from '../services/auditLogger.js'

export class CollabAuthHandler {
  constructor(config) {
    this.config = config
  }

  /**
   * Get the verification key based on the configured algorithm.
   * RS256 uses the public key; HS256 uses the shared secret.
   */
  getVerificationKey() {
    if (this.config.jwt.algorithm === 'RS256' && this.config.jwt.publicKey) {
      return this.config.jwt.publicKey
    }
    return this.config.jwt.secret
  }

  /**
   * Verify a JWT token with dual-algorithm support.
   * Tries the primary algorithm first, then falls back to HS256 during migration.
   * 
   * @param {string} token 
   * @returns {object} Decoded token payload
   * @throws {Error} If both algorithms fail
   */
  verifyToken(token) {
    const verifyKey = this.getVerificationKey()

    if (!verifyKey) {
      throw new Error('No JWT verification key configured. Set JWT_PUBLIC_KEY_PATH (RS256) or JWT_SECRET (HS256).')
    }

    try {
      return jwt.verify(token, verifyKey, {
        algorithms: [this.config.jwt.algorithm],
      })
    } catch (primaryError) {
      // RS256 failed — try HS256 fallback if secret is available
      if (this.config.jwt.algorithm === 'RS256' && this.config.jwt.secret) {
        try {
          const decoded = jwt.verify(token, this.config.jwt.secret, {
            algorithms: ['HS256'],
          })
          console.log(`[Auth] Token verified via HS256 fallback — migration still in progress`)
          return decoded
        } catch (_fallback) {
          // Both failed, throw original
        }
      }
      throw primaryError
    }
  }

  /**
   * Authenticate a WebSocket connection
   * @param {Object} data - { documentName, token }
   * @returns {Promise<Object>} Auth context
   */
  async authenticate(data) {
    const { documentName, token } = data

    // Token is required
    if (!token) {
      throw new Error('Authentication token required')
    }

    try {
      // Verify JWT with dual-algorithm support
      const decoded = this.verifyToken(token)

      // Validate token payload
      if (!decoded.sub || !decoded.documentId || !decoded.role) {
        throw new Error('Invalid token payload')
      }

      // Document name must match token
      if (decoded.documentId !== documentName) {
        throw new Error('Token document mismatch')
      }

      // Validate role
      if (!Object.values(COLLAB_ROLES).includes(decoded.role)) {
        throw new Error('Invalid permission role')
      }

      // Get role capabilities
      const capabilities = COLLAB_ROLE_CAPABILITIES[decoded.role]
      
      if (!capabilities) {
        throw new Error('Unknown role')
      }

      // Build user info
      const userEmail = decoded.sub.toLowerCase()
      const userName = decoded.name || userEmail.split('@')[0]
      const userColor = getCollabUserColor(userEmail)

      console.log(`[Auth] Authenticated: ${userEmail} as ${decoded.role} for ${documentName}`)
      logAuthEvent('collab_connect', 'success', userEmail, { document: documentName, role: decoded.role })

      // Return context to be attached to connection
      return {
        user: {
          email: userEmail,
          name: userName,
          color: userColor,
        },
        role: decoded.role,
        canEdit: capabilities.canEdit,
        documentId: documentName,
        connectionId: `conn-${Date.now()}`,
      }
    } catch (error) {
      if (error instanceof jwt.TokenExpiredError) {
        console.log(`[Auth] Token expired for ${documentName}`)
        throw new Error('Token expired')
      }
      if (error instanceof jwt.JsonWebTokenError) {
        console.log(`[Auth] Invalid token for ${documentName}:`, error.message)
        throw new Error('Invalid token')
      }
      
      console.error(`[Auth] Authentication error:`, error)
      logAuthEvent('collab_auth_failed', 'failed', null, { document: documentName, error: error.message })
      throw error
    }
  }

  /**
   * Parse expiry string to seconds
   * @param {string} expiry 
   * @returns {number}
   */
  parseExpiry(expiry) {
    const match = expiry.match(/^(\d+)([smhd])$/)
    if (!match) return 86400 // Default 24h

    const value = parseInt(match[1], 10)
    const unit = match[2]

    switch (unit) {
      case 's': return value
      case 'm': return value * 60
      case 'h': return value * 3600
      case 'd': return value * 86400
      default: return 86400
    }
  }
}
