<?php

declare(strict_types=1);

namespace Webmail\Services;

/**
 * IdempotencyService
 *
 * Computes deterministic keys for outbox rows so the same logical
 * operation is never executed twice against IMAP. Two motivations:
 *
 *   1. Crash recovery. If the worker dies mid-batch (process killed,
 *      OOM, server reboot), the supervisor's reaper resets `running`
 *      rows back to `pending` after 5 minutes. We MUST NOT replay an
 *      already-completed `\Seen` flag write (harmless) but we also MUST
 *      NOT replay a `move` (the second move would target an UID that
 *      no longer exists, or worse, move the user's NEW message at that
 *      UID slot).
 *
 *   2. Client retry. The frontend retries failed writes; without a
 *      stable idempotency key two retries would create two outbox
 *      rows and the worker would happily execute both.
 *
 * The key is a sha256 hex digest over a stable input shape:
 *   user|account|op|folder_id|uid|target_folder_id|nonce
 *
 * - `nonce` defaults to today's date (UTC). This means the same user
 *   marking the same UID read twice on the same day collapses into
 *   one outbox row. Across day boundaries the operation is allowed to
 *   re-enqueue (a manual mark-read on day 2 should be honoured even
 *   if a stale enqueue from day 1 happens to be in the queue, because
 *   the user actually clicked the button again).
 *
 * - Callers that want a single-shot guarantee regardless of time pass
 *   an explicit nonce (e.g. a UUID generated by the frontend or
 *   derived from the request id). Callers that want a per-day collapse
 *   pass nonce='' and let computeKey fall back to date.
 */
final class IdempotencyService
{
    /**
     * Compute the stable idempotency key for an outbox op.
     *
     * @param string      $userEmail       Owning user (login email).
     * @param string      $accountEmail    IMAP account email (= user for primary, oauth for secondaries).
     * @param string      $op              Outbox op enum value (set_flag, move, delete, ...).
     * @param string|null $folderId        Source folder identity UUID (NULL for create_folder).
     * @param int|null    $uid             IMAP UID at source (NULL for folder-level ops).
     * @param string|null $targetFolderId  Destination folder identity UUID (move/copy).
     * @param string      $nonce           Optional caller-supplied nonce; empty -> per-day collapse.
     */
    public function computeKey(
        string $userEmail,
        string $accountEmail,
        string $op,
        ?string $folderId,
        ?int $uid,
        ?string $targetFolderId = null,
        string $nonce = ''
    ): string {
        if ($nonce === '') {
            // Per-day collapse keeps the queue self-deduplicating for the
            // common case of "user clicked read 3 times because the UI
            // didn't respond instantly". Stale day-old enqueues are reaped
            // by the worker before the day rolls over.
            $nonce = gmdate('Y-m-d');
        }
        $parts = [
            strtolower($userEmail),
            strtolower($accountEmail),
            $op,
            $folderId ?? '',
            $uid !== null ? (string)$uid : '',
            $targetFolderId ?? '',
            $nonce,
        ];
        return hash('sha256', implode('|', $parts));
    }

    /**
     * Per-request UUID-style nonce. Use when the caller wants the
     * idempotency key to depend on this specific request instance,
     * not on the day. The most common consumer is the
     * "user pressed undo" flow where the same op is legitimately
     * enqueued twice in quick succession and must NOT collapse.
     */
    public function generateNonce(): string
    {
        // 16 random bytes -> 32 hex chars. Cryptographic randomness is
        // unnecessary here (this is not a security boundary, just a
        // uniqueness boundary), but random_bytes is the most portable
        // randomness primitive available on every supported PHP.
        return bin2hex(random_bytes(16));
    }
}
