<?php

declare(strict_types=1);

namespace VpsAdmin\Agent\Provisioner\Step\Steps\Create;

use VpsAdmin\Agent\Lib\Validator;
use VpsAdmin\Agent\Provisioner\Step\AbstractStep;
use VpsAdmin\Agent\Provisioner\Step\CompensationPolicy;
use VpsAdmin\Agent\Provisioner\Step\Saga\StepName;
use VpsAdmin\Agent\Provisioner\Step\SiteContext;
use VpsAdmin\Agent\Provisioner\Step\StepEvent;
use VpsAdmin\Agent\Provisioner\Step\StepResult;
use VpsAdmin\Agent\Provisioner\Step\StepState;

/**
 * Seed the PowerDNS zone for a freshly-provisioned site.
 *
 * Writes the canonical record set the panel has been hand-rolling for
 * legacy sites for years (mirrors what the operator showed us as the
 * desired template):
 *
 *   SOA   <domain>           ns1 admin serial 10800 3600 604800 3600
 *   NS    <domain>           ns1.<configured>
 *   NS    <domain>           ns2.<configured>
 *   A     <domain>           <server-ip>
 *   A     mail.<domain>      <server-ip>
 *   CNAME www.<domain>       <domain>
 *   CNAME ftp.<domain>       <domain>
 *   CNAME autodiscover.<domain>  mail.<domain>
 *   CNAME autoconfig.<domain>    mail.<domain>
 *   MX    <domain>     prio 10  mail.<domain>
 *   SRV   _autodiscover._tcp.<domain>  0 443 mail.<domain>
 *   SRV   _imaps._tcp.<domain>         1 993 mail.<domain>
 *   SRV   _submission._tcp.<domain>    1 587 mail.<domain>
 *   TXT   <domain>           v=spf1 a mx ip4:<server-ip> -all
 *   TXT   _dmarc.<domain>    v=DMARC1; p=reject; adkim=s; aspf=s; pct=100;
 *                            rua=mailto:postmaster@<domain>; fo=1
 *
 * The autodiscover/autoconfig CNAMEs + SRV records let mail clients
 * (Outlook, Thunderbird, Apple Mail, eM Client) self-configure from
 * just an address + password — important for migrated users.
 *
 * DKIM is INTENTIONALLY OMITTED here. The DKIM TXT depends on a
 * key-pair generated by OpenDKIM at mail-domain provisioning time; the
 * mail saga adds it once the key exists. Adding a placeholder DKIM
 * here would either break SMTP signing verification or require a
 * later-step rewrite, both worse than just not having the record yet.
 *
 * Skip rules (early returns from execute()):
 *   - Single-label hostname (no dot, e.g. "test6"). Public DNS zones
 *     require an FQDN; the step logs a SKIPPED event and persists
 *     {dns_skipped: 'single-label'} so the UI can render a clear
 *     "no DNS zone (single-label site)" hint instead of "0 records".
 *   - payload['dns_enabled'] === false. Operators using external DNS
 *     (Cloudflare, Route53, etc.) opt out via the modal toggle.
 *
 * Idempotence:
 *   - check() returns true iff a dns_domains row exists for the domain.
 *     We do NOT verify every individual record - check is a "should I
 *     run execute" gate, not a deep audit. execute() is record-by-record
 *     idempotent: each INSERT is preceded by an existence test on
 *     (domain_id, name, type, content), so a re-run after partial
 *     failure tops up missing records without duplicating existing ones.
 *
 * Compensation: SAFE_ROLLBACK.
 *   - If we CREATED the zone (state.data['created_zone'] === true) and a
 *     later step fails, compensate() drops the zone and all its records.
 *   - If the zone PRE-EXISTED (operator hand-built it before kicking off
 *     the saga), compensate() leaves it alone - the operator's data is
 *     not ours to delete.
 *   - If we only ADDED records to a pre-existing zone, compensate
 *     deletes only the records we inserted (tracked in
 *     state.data['inserted_record_ids']).
 *
 * Notify:
 *   - After creating/updating records, the step calls
 *     `pdns_control notify <domain>` so PowerDNS picks the changes up
 *     immediately. The notify is best-effort: a failure logs a warning
 *     event but does NOT fail the step (the records are written; AXFR
 *     will pick them up on the next poll).
 */
final class DnsZoneCreateStep extends AbstractStep
{
    /**
     * @param string $serverIp Public IPv4 the A records point at.
     *                         Resolved at SagaRegistry construction
     *                         time from agent/config.php's `server.ip`
     *                         so a wrong-IP zone would fail-loud at
     *                         worker boot rather than silently per-job.
     * @param string $ns1      Authoritative NS hostname #1 (FQDN, no
     *                         trailing dot - PowerDNS adds it).
     * @param string $ns2      Authoritative NS hostname #2 (FQDN).
     * @param int $defaultTtl  TTL for the seeded records. 3600 matches
     *                         the legacy template.
     */
    public function __construct(
        private readonly string $serverIp,
        private readonly string $ns1,
        private readonly string $ns2,
        private readonly int $defaultTtl = 3600,
    ) {
    }

    public function name(): string
    {
        return StepName::DNS_ZONE_CREATE;
    }

    public function compensationPolicy(): CompensationPolicy
    {
        return CompensationPolicy::SAFE_ROLLBACK;
    }

    public function check(SiteContext $ctx, StepState $state): bool
    {
        $domain = $ctx->domain();

        // A skipped step is "complete" by definition - check() must
        // return true so the orchestrator doesn't infinitely re-run
        // execute() looking for a state we'll never reach.
        if ($this->shouldSkip($ctx, $domain)) {
            return true;
        }

        $pdo = $ctx->database->pdo();
        $stmt = $pdo->prepare("SELECT id FROM dns_domains WHERE name = ? LIMIT 1");
        $stmt->execute([$domain]);
        return (bool) $stmt->fetchColumn();
    }

    public function execute(SiteContext $ctx, StepState $state): StepResult
    {
        $domain = $ctx->domain();

        $skipReason = $this->shouldSkip($ctx, $domain);
        if ($skipReason !== null) {
            return StepResult::skipped(
                $state->mergeData(['dns_skipped' => $skipReason])->withCompleted(),
                "dns zone not seeded: {$skipReason}",
            );
        }

        $pdo = $ctx->database->pdo();
        $events = [];

        $stmt = $pdo->prepare("SELECT id FROM dns_domains WHERE name = ? LIMIT 1");
        $stmt->execute([$domain]);
        $existingId = $stmt->fetchColumn();

        $createdZone = false;
        if ($existingId === false) {
            $insert = $pdo->prepare(
                "INSERT INTO dns_domains (name, type) VALUES (?, 'NATIVE')"
            );
            $insert->execute([$domain]);
            $zoneId = (int) $pdo->lastInsertId();
            $createdZone = true;
            $events[] = StepEvent::info('dns zone created', [
                'domain' => $domain,
                'zone_id' => $zoneId,
            ]);
        } else {
            $zoneId = (int) $existingId;
            $events[] = StepEvent::info('dns zone already present, topping up records', [
                'domain' => $domain,
                'zone_id' => $zoneId,
            ]);
        }

        $insertedIds = (array) ($state->data['inserted_record_ids'] ?? []);
        $records = $this->templateRecords($domain);

        foreach ($records as $rec) {
            $existsStmt = $pdo->prepare(
                "SELECT id FROM dns_records
                 WHERE domain_id = ? AND name = ? AND type = ? AND content = ?
                 LIMIT 1"
            );
            $existsStmt->execute([$zoneId, $rec['name'], $rec['type'], $rec['content']]);
            if ($existsStmt->fetchColumn() !== false) {
                continue;
            }

            $insertStmt = $pdo->prepare(
                "INSERT INTO dns_records (domain_id, name, type, content, ttl, prio)
                 VALUES (?, ?, ?, ?, ?, ?)"
            );
            $insertStmt->execute([
                $zoneId,
                $rec['name'],
                $rec['type'],
                $rec['content'],
                $rec['ttl'],
                $rec['prio'],
            ]);
            $insertedIds[] = (int) $pdo->lastInsertId();
        }

        $events[] = StepEvent::info('dns records seeded', [
            'domain' => $domain,
            'inserted' => count($insertedIds),
        ]);

        $this->bestEffortNotify($ctx, $domain, $events);

        return StepResult::success(
            $state->mergeData([
                'dns_zone_id' => $zoneId,
                'created_zone' => $createdZone,
                'inserted_record_ids' => $insertedIds,
                'dns_skipped' => null,
            ])->withCompleted(),
            $events,
            ['inserted_records' => count($insertedIds)],
        );
    }

    public function compensate(SiteContext $ctx, StepState $state): StepResult
    {
        $zoneId = $state->data['dns_zone_id'] ?? null;
        if ($zoneId === null) {
            return StepResult::success(
                $state,
                [StepEvent::info('compensate: dns step never ran, no-op')]
            );
        }

        $pdo = $ctx->database->pdo();
        $events = [];

        if (!empty($state->data['created_zone'])) {
            $pdo->prepare("DELETE FROM dns_records WHERE domain_id = ?")->execute([$zoneId]);
            $pdo->prepare("DELETE FROM dns_domains WHERE id = ?")->execute([$zoneId]);
            $events[] = StepEvent::info('compensate: dns zone dropped (we created it)', [
                'zone_id' => $zoneId,
            ]);
            return StepResult::success($state, $events);
        }

        $insertedIds = (array) ($state->data['inserted_record_ids'] ?? []);
        if (!empty($insertedIds)) {
            $placeholders = implode(',', array_fill(0, count($insertedIds), '?'));
            $pdo->prepare("DELETE FROM dns_records WHERE id IN ({$placeholders})")
                ->execute($insertedIds);
            $events[] = StepEvent::info('compensate: removed records we inserted', [
                'zone_id' => $zoneId,
                'records' => count($insertedIds),
            ]);
        } else {
            $events[] = StepEvent::info('compensate: pre-existing zone, nothing to undo');
        }

        return StepResult::success($state, $events);
    }

    /**
     * Returns null when the step should run normally, or a short reason
     * string ('single-label' / 'dns_enabled=false') when it should skip.
     */
    private function shouldSkip(SiteContext $ctx, string $domain): ?string
    {
        if (isset($ctx->payload['dns_enabled']) && $ctx->payload['dns_enabled'] === false) {
            return 'dns_enabled=false';
        }

        if (!Validator::domain($domain)) {
            return 'single-label';
        }

        // Belt-and-braces: a misconfigured worker without server.ip
        // wired through SagaRegistry would otherwise stamp the zone
        // with empty A-record content. Better to skip with a clear
        // reason than poison the DB.
        if ($this->serverIp === '') {
            return 'no-server-ip-configured';
        }

        return null;
    }

    /**
     * Build the canonical record set. A separate method (rather than
     * inline) so the test harness can call it and assert on the exact
     * shape without standing up a full saga.
     *
     * @return list<array{name:string,type:string,content:string,ttl:int,prio:int}>
     */
    public function templateRecords(string $domain): array
    {
        $serial = date('Ymd') . '01';
        $admin = 'admin.' . $domain;
        $soaContent = sprintf(
            '%s. %s. %s 10800 3600 604800 3600',
            $this->ns1,
            $admin,
            $serial,
        );

        $spfContent = sprintf('v=spf1 a mx ip4:%s -all', $this->serverIp);
        $dmarcContent = sprintf(
            'v=DMARC1; p=reject; adkim=s; aspf=s; pct=100; rua=mailto:postmaster@%s; fo=1',
            $domain,
        );

        // prio=0 for non-MX/SRV mirrors the legacy DnsAction insert
        // path. PowerDNS interprets 0 as "no priority" for record types
        // that don't carry one. Using NULL here would clash with
        // schemas where dns_records.prio is NOT NULL DEFAULT 0.
        // Autodiscover / autoconfig so Outlook, Thunderbird, Apple Mail and
        // eM Client can self-configure from just an address + password (no
        // manual server entry). The CNAMEs point clients at mail.<domain>
        // (which serves the autodiscover/autoconfig XML), and the SRV records
        // implement RFC 6186 (_imaps / _submission) plus Outlook's
        // _autodiscover lookup. SRV content is "<weight> <port> <target>" with
        // the priority carried in the prio column, matching the MX convention
        // this zone already uses; all priorities are 0 here.
        $mail = 'mail.' . $domain;

        return [
            ['name' => $domain, 'type' => 'SOA', 'content' => $soaContent, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => $domain, 'type' => 'NS', 'content' => $this->ns1, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => $domain, 'type' => 'NS', 'content' => $this->ns2, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => $domain, 'type' => 'A', 'content' => $this->serverIp, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => $mail, 'type' => 'A', 'content' => $this->serverIp, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => 'www.' . $domain, 'type' => 'CNAME', 'content' => $domain, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => 'ftp.' . $domain, 'type' => 'CNAME', 'content' => $domain, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => 'autodiscover.' . $domain, 'type' => 'CNAME', 'content' => $mail, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => 'autoconfig.' . $domain, 'type' => 'CNAME', 'content' => $mail, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => $domain, 'type' => 'MX', 'content' => $mail, 'ttl' => $this->defaultTtl, 'prio' => 10],
            ['name' => '_autodiscover._tcp.' . $domain, 'type' => 'SRV', 'content' => '0 443 ' . $mail, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => '_imaps._tcp.' . $domain, 'type' => 'SRV', 'content' => '1 993 ' . $mail, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => '_submission._tcp.' . $domain, 'type' => 'SRV', 'content' => '1 587 ' . $mail, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => $domain, 'type' => 'TXT', 'content' => $spfContent, 'ttl' => $this->defaultTtl, 'prio' => 0],
            ['name' => '_dmarc.' . $domain, 'type' => 'TXT', 'content' => $dmarcContent, 'ttl' => $this->defaultTtl, 'prio' => 0],
        ];
    }

    private function bestEffortNotify(SiteContext $ctx, string $domain, array &$events): void
    {
        $adapters = $ctx->adapters();
        if ($adapters === null) {
            $events[] = StepEvent::warning('pdns_control notify skipped: no adapters bag');
            return;
        }

        try {
            $result = $adapters->runner->run('pdns_control', ['notify', $domain], null, 5);
            if ($result->isSuccess()) {
                $events[] = StepEvent::info('pdns_control notify sent', ['domain' => $domain]);
            } else {
                $events[] = StepEvent::warning('pdns_control notify exited non-zero', [
                    'domain' => $domain,
                    'exit_code' => $result->exitCode,
                    'stderr_excerpt' => substr((string) $result->stderr, 0, 200),
                ]);
            }
        } catch (\Throwable $e) {
            $events[] = StepEvent::warning('pdns_control notify failed to launch', [
                'domain' => $domain,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
