<?php
/**
 * Mail Pod Bridge
 *
 * On Docker boxes the whole mail tier (Postfix, Dovecot, OpenDKIM, ...) runs
 * inside the flowone-mail-1 container ("mail pod"), so native tooling like
 * `systemctl is-active postfix`, `postconf` or `doveadm` either fails or
 * reports a false "Stopped" on the host. This bridge detects that layout and
 * proxies the same commands through `docker exec` into the pod.
 *
 * Actions consult it ONLY when the native postfix systemd unit does not
 * exist, so native installs keep their exact behavior.
 */

namespace VpsAdmin\Agent\Lib;

class MailPodBridge
{
    /** Mail pod container name (compose project "flowone", service "mail"). */
    public const POD = 'flowone-mail-1';

    /** @var callable(string, array, int): array  execCommand from the action */
    private $execCommand;

    private ?bool $active = null;

    public function __construct(callable $execCommand)
    {
        $this->execCommand = $execCommand;
    }

    /**
     * True when mail on this box is served by the Docker mail pod:
     * the native postfix unit is absent AND the pod container is running.
     */
    public function active(): bool
    {
        if ($this->active !== null) {
            return $this->active;
        }

        $unit = ($this->execCommand)('systemctl', ['show', '-p', 'LoadState', '--value', 'postfix'], 10);
        if (trim($unit['output']) !== 'not-found') {
            return $this->active = false;
        }

        $res = ($this->execCommand)('docker', ['inspect', '--format', '{{.State.Status}}', self::POD], 10);
        return $this->active = ($res['success'] && trim($res['output']) === 'running');
    }

    /** Run a command inside the mail pod. Args are escaped individually. */
    public function exec(array $cmd, int $timeout = 30): array
    {
        return ($this->execCommand)('docker', array_merge(['exec', self::POD], $cmd), $timeout);
    }

    /** Whether a supervised program (postfix, dovecot, ...) is RUNNING. */
    public function programRunning(string $program): bool
    {
        $res = $this->exec(['supervisorctl', 'status', $program], 20);
        return (bool) preg_match('/\bRUNNING\b/', $res['output']);
    }

    /** Restart a supervised program inside the pod. */
    public function restartProgram(string $program): array
    {
        return $this->exec(['supervisorctl', 'restart', $program], 60);
    }

    /**
     * Read `key = value` style output (postconf/doveconf accept multiple
     * keys per invocation) into a map — one docker exec for all keys.
     */
    public function keyValues(string $binary, array $keys, int $timeout = 30): array
    {
        if ($keys === []) {
            return [];
        }
        $res = $this->exec(array_merge([$binary], $keys), $timeout);
        $settings = [];
        foreach (explode("\n", $res['output']) as $line) {
            $eq = strpos($line, '=');
            if ($eq === false) {
                continue;
            }
            $key = trim(substr($line, 0, $eq));
            if (in_array($key, $keys, true)) {
                $settings[$key] = trim(substr($line, $eq + 1));
            }
        }
        return $settings;
    }

    /** Read a config file from inside the pod (read-only view). */
    public function readFile(string $path): ?string
    {
        $res = $this->exec(['cat', $path], 20);
        return $res['success'] ? $res['output'] : null;
    }

    /** Whether a file exists inside the pod. */
    public function fileExists(string $path): bool
    {
        $res = $this->exec(['test', '-e', $path], 10);
        return $res['success'];
    }

    /** Uniform error for write operations that the pod does not support. */
    public function readOnlyError(): string
    {
        return 'Mail runs inside the ' . self::POD . ' container on this server. '
            . 'Its configuration is generated by the container image and entrypoint — '
            . 'edit the stack .env (/opt/flowone/.env) and restart the mail container instead.';
    }
}
